### ISSUE TITLE
Issue parsing value when parameter is array

### ISSUE THREAD

**Issue by KrekkieD** [jan-swiecki/php-simple-annotations#2]
#90:

    $this->parameters[$match[1]] = array_merge((array)$this->parameters[$match[1]], (array)$match[2]);

$match[2] should be parsed first before adding to array (as is done in the else):

    $this->parameters[$match[1]] = array_merge((array)$this->parameters[$match[1]], (array)$this->parseValue($match[2]));

Issue reproducible by setting these annotations:

    /*
     * @Lalala ["somejsonarray", "2"]
     * @Lalala ["anotherjsonarray", "3"]
    */

Second param would be string instead of json parsed array

**Comment by jan-swiecki** [comment]
@KrekkieD finally fixed :)
