### ISSUE TITLE
Add possibility to parse property annotation

### ISSUE THREAD

**Issue by vojtatranta** [jan-swiecki/php-simple-annotations#4]
I like the Doctrine way to get ORM config for DB cols, I would like to implement same thing in my project.
So I searched for annotation parsing solution and found your great repo!
However it seems I cannot parse class properties with this tool, could we add this feature?
Thanks.

**Comment by jan-swiecki** [comment]
Thanks for your input! I'm very busy lately but I'll try to add this asap.

**Comment by jan-swiecki** [comment]
@vojtatranta sorry for delay, fixed in dc0a6ba (version 0.3.0). See #5 issue too if it affects you.
